"""Agregado subtitulo y comentarios a Noticia

Revision ID: 2cdf7ece8669
Revises: 66f87be42cf6
Create Date: 2025-03-31 17:45:34.332094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cdf7ece8669'
down_revision = '66f87be42cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentario__noticia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('noticia_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['noticia_id'], ['noticia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitulo', sa.String(length=255), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.drop_column('subtitulo')

    op.drop_table('comentario__noticia')
    # ### end Alembic commands ###
