"""Cambio en modelo Noticia para manejar imágenes

Revision ID: 672240c713a3
Revises: 3f98fae8fe8a
Create Date: 2025-03-21 22:24:39.075788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672240c713a3'
down_revision = '3f98fae8fe8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(length=300), nullable=True))
        batch_op.drop_column('imagen_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###
