"""Cambio de video_url a video

Revision ID: 9fd4b11af869
Revises: 672240c713a3
Create Date: 2025-03-27 21:53:45.416570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd4b11af869'
down_revision = '672240c713a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video', sa.String(length=300), nullable=True))
        batch_op.drop_column('video_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('video')

    # ### end Alembic commands ###
